package opioid.model;


public class BeneficiaryInfo {
	protected int doctorId;
	protected int beneCount;
	protected int opiBenCount;
	protected int erOpiBenCount;
	protected int antibioBenCount;
	protected int benAgeL65;
	protected double benAgeG65;
	protected int avgAgeBen;
	protected int benF;
	protected int benM;
	protected int benNDual;
	protected int benDual;
	protected double benAvgRisk;
	
	
	// This constructor can be used for reading records from MySQL, where we have all fields,
	// including the PostId.
	public BeneficiaryInfo(int doctorId, int beneCount, int opiBenCount, int erOpiBenCount, int antibioBenCount,
			int benAgeL65, double benAgeG65, int avgAgeBen, int benF, int benM, int benNDual, 
			int benDual, double benAvgRisk) {
		this.doctorId = doctorId;
		this.beneCount = beneCount;
		this.opiBenCount = opiBenCount;
		this.erOpiBenCount = erOpiBenCount;
		this.antibioBenCount = antibioBenCount;
		this.benAgeL65 = benAgeL65;
		this.benAgeG65 = benAgeG65;
		this.avgAgeBen = avgAgeBen;
		this.benF = benF;
		this.benM = benM;
		this.benNDual = benNDual;
		this.benDual = benDual;
		this.benAvgRisk = benAvgRisk;
	
	}
	
	// This constructor can be used for reading records from MySQL, where we only have the postId,
	// such as a foreign key reference to PostId.
	// Given PostId, we can fetch the full BlogPost record.
	public BeneficiaryInfo(int doctorId) {
		this.doctorId = doctorId;
	}
	
	// This constructor can be used for creating new records, where the postId may not be
	// assigned yet since it is auto-generated by MySQL.
	public BeneficiaryInfo(int beneCount, int opiBenCount, int erOpiBenCount, int antibioBenCount,
			int benAgeL65, double benAgeG65, int avgAgeBen, int benF, int benM, int benNDual, 
			int benDual, double benAvgRisk) {
		this.beneCount = beneCount;
		this.opiBenCount = opiBenCount;
		this.erOpiBenCount = erOpiBenCount;
		this.antibioBenCount = antibioBenCount;
		this.benAgeL65 = benAgeL65;
		this.benAgeG65 = benAgeG65;
		this.avgAgeBen = avgAgeBen;
		this.benF = benF;
		this.benM = benM;
		this.benNDual = benNDual;
		this.benDual = benDual;
		this.benAvgRisk = benAvgRisk;
	
	
	}
	
	public int getDoctorId() {
		return doctorId;
	}

	public void setDoctorId(int doctorId) {
		this.doctorId = doctorId;
	}
	
	public int getBeneCount() {
		return beneCount;
	}

	public void setBeneCount(int beneCount) {
		this.beneCount = beneCount;
	}
	
	public int getOpiBenCount() {
		return opiBenCount;
	}

	public void setOpiBenCount(int opiBenCount) {
		this.opiBenCount = opiBenCount;
	}

	public int getErOpiBenCount() {
		return erOpiBenCount;
	}

	public void setErOpiBenCount(int erOpiBenCount) {
		this.erOpiBenCount = erOpiBenCount;
	}
	
	public int getAntiBioBenCount() {
		return antibioBenCount;
	}

	public void setAntiBioBenCount(int antibioBenCount) {
		this.antibioBenCount = antibioBenCount;
	}
	
	public int getBenAgeL65() {
		return benAgeL65;
	}

	public void setBenAgeL65(int benAgeL65) {
		this.benAgeL65 = benAgeL65;
	}
	
	public double getBenAgeG65() {
		return benAgeG65;
	}

	public void setBenAgeG65(double benAgeG65) {
		this.benAgeG65 = benAgeG65;
	}
	
	public int getAvgAgeBen() {
		return avgAgeBen;
	}

	public void setAvgAgeBen(int avgAgeBen) {
		this.avgAgeBen = avgAgeBen;
	}
	
	public int getBenF() {
		return benF;
	}

	public void setBenF(int benF) {
		this.benF = benF;
	}
	
	public int getBenM() {
		return benM;
	}

	public void setBenM(int benM) {
		this.benM = benM;
	}
	
	public int getBenNDual() {
		return benNDual;
	}

	public void setBenNDual(int benNDual) {
		this.benNDual = benNDual;
	}
	
	public int getBenDual() {
		return benDual;
	}

	public void setBenDual(int benDual) {
		this.benDual = benDual;
	}
	
	public double getBenAvgRisk() {
		return benAvgRisk;
	}

	public void setBenAvgRisk(int benAvgRisk) {
		this.benAvgRisk = benAvgRisk;
	}
}
