package opioid.model;

public class ClaimInfo {
	protected int doctorId;
	protected int totalClaimCount;
	protected int dayFill30;
	protected int brandClaimCount;
	protected int genericClaim;
	protected int opioidClaim;
	protected int erOpioidClaim;
	protected int antiClaim;
	
	// This constructor can be used for reading records from MySQL, where we have all fields,
	// including the PostId.
	public ClaimInfo(int doctorId, int totalClaimCount, int dayFill30, int brandClaimCount, int genericClaim,
			int opioidClaim, int erOpioidClaim, int antiClaim) {
		this.doctorId = doctorId;
		this.totalClaimCount = totalClaimCount;
		this.dayFill30 = dayFill30;
		this.brandClaimCount = brandClaimCount;
		this.genericClaim = genericClaim;
		this.opioidClaim = opioidClaim;
		this.erOpioidClaim = erOpioidClaim;
		this.antiClaim = antiClaim;
	
	}
	
	// This constructor can be used for reading records from MySQL, where we only have the postId,
	// such as a foreign key reference to PostId.
	// Given PostId, we can fetch the full BlogPost record.
	public ClaimInfo(int doctorId) {
		this.doctorId = doctorId;
	}
	
	// This constructor can be used for creating new records, where the postId may not be
	// assigned yet since it is auto-generated by MySQL.
	public ClaimInfo(int totalClaimCount, int dayFill30, int brandClaimCount, int genericClaim,
			int opioidClaim, int erOpioidClaim, int antiClaim) {
		this.totalClaimCount = totalClaimCount;
		this.dayFill30 = dayFill30;
		this.brandClaimCount = brandClaimCount;
		this.genericClaim = genericClaim;
		this.opioidClaim = opioidClaim;
		this.erOpioidClaim = erOpioidClaim;
		this.antiClaim = antiClaim;
	
	}
	
	public int getDoctorId() {
		return doctorId;
	}

	public void setDoctorId(int doctorId) {
		this.doctorId = doctorId;
	}

	public int getTotalClaimCount() {
		return totalClaimCount;
	}

	public void setTotalClaimCount(int totalClaimCount) {
		this.totalClaimCount = totalClaimCount;
	}
	
	public int getDayFill30() {
		return dayFill30;
	}

	public void setDayFill30(int dayFill30) {
		this.dayFill30 = dayFill30;
	}
	
	public int getBrandClaimCount() {
		return brandClaimCount;
	}

	public void setBrandClaimCount(int brandClaimCount) {
		this.brandClaimCount = brandClaimCount;
	}
	
	public int getGenericClaim() {
		return genericClaim;
	}

	public void setGenericClaim(int genericClaim) {
		this.genericClaim = genericClaim;
	}
	
	public int getOpioidClaim() {
		return opioidClaim;
	}

	public void setOpioidClaim(int opioidClaim) {
		this.opioidClaim = opioidClaim;
	}
	
	public int getErOpioidClaim() {
		return erOpioidClaim;
	}

	public void setErOpioidClaim(int erOpioidClaim) {
		this.erOpioidClaim = erOpioidClaim;
	}

	public int getAntiClaim() {
		return antiClaim;
	}

	public void setAntiClaim(int antiClaim) {
		this.antiClaim = antiClaim;
	}

}